### ISSUE TITLE
Pinephone (Braveheart) keeps turning off

### ISSUE THREAD

**Issue by niansa** [GloDroid/glodroid_device#24]
Hey, with GloDroid my Pinephone Braveheart edition keeps turning off on following events:
 - Updating/Installing any package
 - Entering standby (fixed by disabling modem using killswitch)
 - Setting up Telegram Messenger (verification code)
 - Charging battery to 100%

It is booted from SD Card and has been connected to USB for charging all the time.

**Comment by niansa** [comment]
Tried with boot from emmc this time getting a random turn off by opening the settings.

The random turn-off when installing or updating apps seems fixed by booting from emmc

**Comment by rsglobal** [comment]
I'm afraid this issue is the one from `we can't reproduce on our end` list.

**Comment by rsglobal** [comment]
Could you re-validate on our latest 0.7.0 release and if issue is still present open the issue in our manifest repository?

https://github.com/GloDroid/glodroid_manifest/issues
